### ISSUE TITLE
Not sure what this mod do but need def files to make it work

### ISSUE THREAD

**Issue by Ganondorf91** [PsykoDev/HiddenLoc#1]
Error: [dispatch] write: failed to generate C_STATUS_FL<1>:
Error: no definition found for message (name: "C_STATUS_FL", code: 36133, version: 1)

**Comment by PsykoDev** [comment]
https://github.com/PsykoDev/Full-Opcode-Tera-EU-NA
https://github.com/PsykoDev/Last-Def-Files
use that to obtain missing def files / opcode

**Comment by PsykoDev** [comment]
this mod remove your last location in guild panel and keep your status offline in friend list

**Comment by Ganondorf91** [comment]
Ah nice, I've no use for that but will try it anyways :)
